# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches:
      - main
      - develop
      - development
      - 2024-11-08-GHworkflow
  pull_request:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.5.1"

    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install tesseract-ocr libtesseract-dev
        uv sync --all-extras --dev

    - name: Run Ruff
      run: uv run ruff check --output-format=github .

    - name: Ensure browsers are installed for playwright
      run: uv run playwright install --with-deps chromium

    - name: Test with pytest
      run: |
        uv run pytest
